language: python
python:
    - "3.4"

# Docker testing
sudo: required
services:
    - docker

# Install dependencies
install:
    - "pip3 install --upgrade tox -r test-requirements.txt"

# Run tests
script: ./test.sh
